DROP SEQUENCE TYDEETABLESEQ;
DROP TABLE TYDEETABLETEST;

CREATE SEQUENCE TYDEETABLESEQ;
CREATE TABLE TYDEETABLETEST(
	SEQ NUMBER PRIMARY KEY,
	NAME VARCHAR2(100) NOT NULL,
	PARENT_SEQ NUMBER,
	REGDATE DATE NOT NULL
);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '방1', NULL, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '거실', NULL, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '방2', NULL, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '부엌', NULL, SYSDATE);

INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '책장', 1, SYSDATE); --5
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '3층', 5, SYSDATE); --6
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '우리가 빛의 속도로 갈 수 없다면', 6, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '전쟁은 여자의 얼굴을 하지 않았다', 6, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '지구에서 한아뿐', 6, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '마우스가드 RPG', 6, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '미스테리아 25호', 6, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '안녕 드뷔시', 6, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '항상 앞부분만 쓰다가 그만두는 당신을 위한 어떻게든 글쓰기', 6, SYSDATE);

INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '2층', 5, SYSDATE); --14
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '비밀의 화원', 14, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '룬의 아이들', 14, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '하얀 늑대들', 14, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '빨간머리 앤', 14, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '태양의 아이들', 14, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '끝없는 이야기', 14, SYSDATE);

INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, 'TV', 2, SYSDATE);

INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '옷장', 1, SYSDATE);

INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '네냐플 티셔츠', 22, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '골지 민소매', 22, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '꽃무늬 롱원피스', 22, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '꽃무늬 스커트', 22, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '하와이안 셔츠', 22, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '무지 흰티셔츠', 22, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '매드맥스 티셔츠', 22, SYSDATE);
INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '빈티지 체크무늬 원피스', 22, SYSDATE);

INSERT INTO TYDEETABLETEST VALUES(TYDEETABLESEQ.NEXTVAL, '서랍', 2, SYSDATE);

SELECT SEQ, NAME, PARENT_SEQ, REGDATE FROM TYDEETABLETEST;

SELECT LEVEL, LPAD(' ', 2*(LEVEL-1)) || NAME "NAME", SEQ, PARENT_SEQ, REGDATE
FROM TYDEETABLETEST 
START WITH SEQ IN (SELECT SEQ FROM TYDEETABLETEST WHERE PARENT_SEQ IS NULL)
CONNECT BY PRIOR SEQ = PARENT_SEQ
ORDER SIBLINGS BY SEQ;

SELECT DISTINCT LEVEL
FROM TYDEETABLETEST 
START WITH SEQ IN (SELECT SEQ FROM TYDEETABLETEST WHERE PARENT_SEQ IS NULL)
CONNECT BY PRIOR SEQ = PARENT_SEQ
ORDER BY LEVEL;

SELECT DISTINCT PARENT_SEQ
FROM TYDEETABLETEST
START WITH SEQ IN (SELECT SEQ FROM TYDEETABLETEST WHERE PARENT_SEQ IS NULL)
CONNECT BY PRIOR SEQ = PARENT_SEQ
ORDER BY PARENT_SEQ DESC;

--SELECT LEVEL, SEQ, NAME, PARENT_SEQ, REGDATE
SELECT COUNT(*)
FROM TYDEETABLETEST 
WHERE LEVEL = 4
AND PARENT_SEQ = 6
START WITH SEQ IN (SELECT SEQ FROM TYDEETABLETEST WHERE PARENT_SEQ IS NULL)
CONNECT BY PRIOR SEQ = PARENT_SEQ
ORDER BY PARENT_SEQ, SEQ;

SELECT LEV, NAME, SEQ, PARENT_SEQ, REGDATE
FROM (SELECT LEVEL "LEV", NAME, SEQ, PARENT_SEQ, REGDATE
		FROM TYDEETABLETEST
		START WITH SEQ IN (SELECT SEQ FROM TYDEETABLETEST WHERE PARENT_SEQ = 0)
		CONNECT BY PRIOR SEQ = PARENT_SEQ
		ORDER SIBLINGS BY SEQ)
WHERE LEV = 1
AND PARENT_SEQ = 0;
