DROP SEQUENCE USER_INFO_SEQ;
DROP TABLE USER_INFO;
CREATE SEQUENCE USER_INFO_SEQ;

CREATE TABLE USER_INFO(
	USER_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(500) NOT NULL,
	USER_PW VARCHAR2(1000) NOT NULL,
	USER_ROLE VARCHAR2(100) NOT NULL,
	USER_NICKNAME VARCHAR2(500) NOT NULL,
	USER_REGDATE DATE NOT NULL,
	SNS_TYPE VARCHAR2(20),
	SNS_ID VARCHAR2(500),
	USER_ACTIVE VARCHAR2(20) NOT NULL,
	CONSTRAINTS USER_ACTIVE_CK CHECK(USER_ACTIVE IN('Y','N')),
	CONSTRAINTS USER_ID_UQ UNIQUE(USER_ID),
	CONSTRAINTS USER_NICKNAME_UQ UNIQUE(USER_NICKNAME),
	CONSTRAINTS SNS_TYPE_CK CHECK(SNS_TYPE IN('G','N','K')),
	CONSTRAINTS SNS_ID_UQ UNIQUE(SNS_ID)
);

INSERT INTO USER_INFO VALUES
(USER_INFO_SEQ.NEXTVAL, 'tydee.adm@gmail.com', 'messy071520', 'ADMIN', '관리자', SYSDATE, NULL, NULL, 'Y');


INSERT INTO USER_INFO 
VALUES(USER_INFO_SEQ.NEXTVAL, 'test@tydee.com', 'tydee1234', 'USER', 'test', SYSDATE, NULL, NULL, 'Y');


SELECT USER_NO, USER_ID, USER_PW, USER_ROLE, USER_NICKNAME, USER_REGDATE, SNS_TYPE, SNS_ID, USER_ACTIVE
FROM USER_INFO;





